-- MassTransit EF Core transactional outbox (BACKLOG.md item F §2.3): the schema MassTransit's
-- AddInboxStateEntity/AddOutboxMessageEntity/AddOutboxStateEntity expect, generated via
-- `dotnet ef migrations script` against MassTransit.EntityFrameworkCore 8.3.7 and hand-adapted
-- to this repo's idempotent-migration convention. Table names are suffixed _observation since
-- this service shares one physical Postgres database with the others (see CLAUDE.md).

CREATE TABLE IF NOT EXISTS inbox_state_observation (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "MessageId" uuid NOT NULL,
    "ConsumerId" uuid NOT NULL,
    "LockId" uuid NOT NULL,
    "RowVersion" bytea,
    "Received" timestamp with time zone NOT NULL,
    "ReceiveCount" integer NOT NULL,
    "ExpirationTime" timestamp with time zone,
    "Consumed" timestamp with time zone,
    "Delivered" timestamp with time zone,
    "LastSequenceNumber" bigint,
    CONSTRAINT "PK_inbox_state_observation" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_inbox_state_observation_MessageId_ConsumerId" UNIQUE ("MessageId", "ConsumerId")
);

CREATE TABLE IF NOT EXISTS outbox_state_observation (
    "OutboxId" uuid NOT NULL,
    "LockId" uuid NOT NULL,
    "RowVersion" bytea,
    "Created" timestamp with time zone NOT NULL,
    "Delivered" timestamp with time zone,
    "LastSequenceNumber" bigint,
    CONSTRAINT "PK_outbox_state_observation" PRIMARY KEY ("OutboxId")
);

CREATE TABLE IF NOT EXISTS outbox_message_observation (
    "SequenceNumber" bigint GENERATED BY DEFAULT AS IDENTITY,
    "EnqueueTime" timestamp with time zone,
    "SentTime" timestamp with time zone NOT NULL,
    "Headers" text,
    "Properties" text,
    "InboxMessageId" uuid,
    "InboxConsumerId" uuid,
    "OutboxId" uuid,
    "MessageId" uuid NOT NULL,
    "ContentType" character varying(256) NOT NULL,
    "MessageType" text NOT NULL,
    "Body" text NOT NULL,
    "ConversationId" uuid,
    "CorrelationId" uuid,
    "InitiatorId" uuid,
    "RequestId" uuid,
    "SourceAddress" character varying(256),
    "DestinationAddress" character varying(256),
    "ResponseAddress" character varying(256),
    "FaultAddress" character varying(256),
    "ExpirationTime" timestamp with time zone,
    CONSTRAINT "PK_outbox_message_observation" PRIMARY KEY ("SequenceNumber"),
    CONSTRAINT "FK_outbox_message_observation_inbox_state_observation_InboxMes~" FOREIGN KEY ("InboxMessageId", "InboxConsumerId") REFERENCES inbox_state_observation ("MessageId", "ConsumerId"),
    CONSTRAINT "FK_outbox_message_observation_outbox_state_observation_OutboxId" FOREIGN KEY ("OutboxId") REFERENCES outbox_state_observation ("OutboxId")
);

CREATE INDEX IF NOT EXISTS "IX_inbox_state_observation_Delivered" ON inbox_state_observation ("Delivered");
CREATE INDEX IF NOT EXISTS "IX_outbox_message_observation_EnqueueTime" ON outbox_message_observation ("EnqueueTime");
CREATE INDEX IF NOT EXISTS "IX_outbox_message_observation_ExpirationTime" ON outbox_message_observation ("ExpirationTime");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_outbox_message_observation_InboxMessageId_InboxConsumerId_S~" ON outbox_message_observation ("InboxMessageId", "InboxConsumerId", "SequenceNumber");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_outbox_message_observation_OutboxId_SequenceNumber" ON outbox_message_observation ("OutboxId", "SequenceNumber");
CREATE INDEX IF NOT EXISTS "IX_outbox_state_observation_Created" ON outbox_state_observation ("Created");
