apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: omyfish
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: omyfish/notification-service:latest
          env:
            - name: RabbitMq__Host
              value: "rabbitmq"
            - name: RabbitMq__Username
              valueFrom:
                secretKeyRef:
                  name: omyfish-secrets
                  key: rabbitmq-username
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: omyfish-secrets
                  key: rabbitmq-password
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
